// Portfolio data — single source of truth.
// `cat` drives the colored accent and icon. `featured` lets a card span 2 cols in bento.
window.PORTFOLIO_PROJECTS = [
  {
    id: 'corona-m5',
    title: 'CoronaVirus Monitor',
    glyph: 'Cv',
    cat: 'project',
    desc: 'Real-time COVID-19 stats on an M5StickC Plus — case counts, deaths and recoveries fetched live and rendered on the built-in display.',
    tech: ['C++', 'Arduino', 'M5StickC Plus'],
    live: null,
    repo: 'https://github.com/ezar/M5StickCPlus-CoronaVirus',
    year: 2021,
    featured: false,
  },
  {
    id: 'claude-desktop-buddy',
    title: 'Claude Desktop Buddy',
    glyph: 'Cb',
    cat: 'project',
    desc: 'ESP32 desk pet that reacts to Claude for Desktop via Bluetooth LE — displays permission prompts, messages and animated GIF packs on an M5StickCPlus.',
    longDesc: 'Fork of the official Anthropic reference implementation. Added support for animated GIF character packs, NVS-backed persistent settings and an extended BLE command set so the pet can react to more Claude event types. Built with PlatformIO and the Arduino framework on top of the Nordic UART Service.',
    tech: ['C++', 'ESP32', 'Arduino', 'BLE', 'PlatformIO'],
    live: null,
    repo: 'https://github.com/ezar/claude-desktop-buddy',
    year: 2025,
    featured: false,
    forked: true,
    forkedFrom: 'anthropics/claude-desktop-buddy',
  },
  {
    id: 'tokenbar',
    title: 'TokenBar',
    glyph: 'Tb',
    cat: 'project',
    desc: 'Desktop system-tray app to monitor AI API quotas in real time — Codex, Claude, GitHub Copilot, OpenAI and Anthropic usage at a glance. Cross-platform core built with Avalonia.',
    tech: ['C#', '.NET 10', 'Avalonia'],
    live: null,
    repo: 'https://github.com/ezar/TokenBar',
    year: 2025,
    featured: false,
  },
  {
    id: 'saludmcp',
    title: 'SaludMCP',
    glyph: 'Sm',
    cat: 'mcp',
    desc: '7 tools over the official AEMPS CIMA drug database — search medications, check supply shortages, safety alerts, generics. No API key, no registration.',
    tech: ['C#', '.NET 10', 'MCP'],
    live: null,
    repo: 'https://github.com/ezar/SaludMCP',
    year: 2025,
    featured: false,
  },
  {
    id: 'stocksagent',
    title: 'Analista Financiero IA',
    glyph: 'Af',
    cat: 'agent',
    desc: 'Personal AI financial analyst. Portfolio with real-time P&L, watchlist, price alerts, news, automatic signals on open, what-if simulator and saved conversations.',
    tech: ['Python', 'Flask', 'Vue 3', 'Chart.js', 'Claude AI', 'yfinance', 'Docker', 'PWA'],
    live: 'https://ezarlive-financial-analyst.hf.space/',
    repo: 'https://github.com/ezar/StocksAgent',
    year: 2025,
    featured: true,
  },
  {
    id: 'home-energy',
    title: 'home-energy',
    glyph: 'He',
    cat: 'project',
    desc: 'Private electricity dashboard — real smart meter data via Datadis API + hourly PVPC prices from Red Eléctrica, bill estimator with tax breakdown, anomaly detection.',
    tech: ['Next.js', 'Supabase', 'Recharts', 'TypeScript'],
    live: 'https://home-energy-sand.vercel.app',
    repo: 'https://github.com/ezar/home-energy',
    year: 2025,
    featured: true,
  },
  {
    id: 'feedwise',
    title: 'feedwise',
    glyph: 'Fw',
    cat: 'project',
    desc: 'RSS / feed reader with AI summaries and Cloudflare Worker background sync.',
    tech: ['Next.js', 'Supabase', 'Cloudflare', 'Claude AI'],
    live: 'https://feedwise-henna.vercel.app',
    repo: 'https://github.com/ezar/feedwise',
    year: 2025,
    featured: false,
  },
  {
    id: 'beat-painter',
    title: 'beat-painter',
    glyph: 'Bp',
    cat: 'project',
    desc: 'Paint with your voice — mic input drives 7 visual modes (bubbles, waves, stars, petals, rain, galaxy, lava) in real time.',
    tech: ['React', 'Web Audio API', 'Canvas 2D', 'PWA'],
    live: 'https://ezar.github.io/beat-painter/',
    repo: 'https://github.com/ezar/beat-painter',
    year: 2025,
    featured: true,
  },
  {
    id: 'bank-radar',
    title: 'bank-radar-es',
    glyph: 'Br',
    cat: 'project',
    desc: 'Proof of concept to search and compare Spanish banking products.',
    tech: ['TypeScript', 'React'],
    live: 'https://bank-radar-es.vercel.app/',
    repo: 'https://github.com/ezar/bank-radar-es',
    year: 2025,
    featured: false,
  },
  {
    id: 'drawvity',
    title: 'Drawvity',
    glyph: 'Dv',
    cat: 'game',
    desc: 'Physics puzzle game. Draw freehand strokes on canvas, launch a ball that rolls and bounces along them to reach the star goal. 40 levels across 4 worlds.',
    tech: ['React 19', 'TypeScript', 'Vite', 'Matter.js', 'Zustand', 'PWA'],
    live: 'https://ezar.github.io/drawvity/',
    repo: 'https://github.com/ezar/drawvity',
    year: 2025,
    featured: true,
  },
  {
    id: 'flag-master',
    title: 'FlagMaster',
    glyph: 'Fm',
    cat: 'game',
    desc: 'Mobile-first educational game to learn world flags as a family. 70+ countries across 5 continents, 6 game modes, mastery system with region unlocks.',
    tech: ['React', 'TypeScript', 'Vite', 'Zustand', 'Framer Motion', 'PWA'],
    live: 'https://ezar.github.io/flag-master/',
    repo: 'https://github.com/ezar/flag-master',
    year: 2024,
    featured: false,
  },
  {
    id: 'nakama-trivia',
    title: 'Nakama Trivia',
    glyph: 'Nt',
    cat: 'game',
    desc: 'One Piece trivia game — 150+ questions across 5 categories, streak multipliers, Berry economy, rank progression and optional Claude AI to generate questions and explain answers.',
    tech: ['React', 'TypeScript', 'Vite', 'Zustand', 'Framer Motion', 'Claude AI', 'PWA'],
    live: 'https://ezar.github.io/nakama-trivia/',
    repo: 'https://github.com/ezar/nakama-trivia',
    year: 2025,
    featured: false,
  },
  {
    id: 'nakama-words',
    title: 'Palabra Hunter',
    glyph: 'Ph',
    cat: 'game',
    desc: 'Pirate-themed EN→ES vocabulary game. 320 words across 15 worlds, Berry economy, 8 pirate ranks, 29 achievements, daily challenge, 750 tests.',
    tech: ['React', 'TypeScript', 'Zustand', 'PWA'],
    live: 'https://ezar.github.io/nakama-words/',
    repo: 'https://github.com/ezar/nakama-words',
    year: 2024,
    featured: false,
  },
  {
    id: 'nakama-math',
    title: 'Nakama Math',
    glyph: 'Nm',
    cat: 'game',
    desc: 'Math practice with One Piece theme. 8 game modes (timed, survival, VS AI, local duel…), 8 difficulty levels from sums to fractions, daily challenge.',
    tech: ['React', 'TypeScript', 'Zustand', 'PWA'],
    live: 'https://ezar.github.io/nakama-math/',
    repo: 'https://github.com/ezar/nakama-math',
    year: 2024,
    featured: false,
  },
  {
    id: 'luffy-island',
    title: 'Luffy Island Quest',
    glyph: 'Li',
    cat: 'game',
    desc: 'Local multiplayer board game for 1–4 players. Sail the Grand Line, land on 6 One Piece islands, each with its own skill minigame.',
    tech: ['React', 'Vite', 'Zustand', 'Framer Motion'],
    live: 'https://ezar.github.io/luffy-island-quest/',
    repo: 'https://github.com/ezar/luffy-island-quest',
    year: 2024,
    featured: false,
  },
  {
    id: 'onepiece',
    title: 'One Piece Game',
    glyph: 'Op',
    cat: 'game',
    desc: 'Create your pirate, choose a Devil Fruit, make 6 story decisions and get your wanted poster with a calculated bounty, downloadable as PNG.',
    tech: ['React', 'Vite', 'Tailwind'],
    live: 'https://ezar.github.io/OnePieceGame/',
    repo: 'https://github.com/ezar/OnePieceGame',
    year: 2024,
    featured: false,
  },
  {
    id: 'colorgame',
    title: 'Color Match',
    glyph: 'Cm',
    cat: 'game',
    desc: 'Spin the color wheel and match the target hue as precisely as you can. Scored 0–100, graded S→F, daily challenge, streak tracker, PWA.',
    tech: ['TypeScript', 'Canvas', 'Vite', 'PWA'],
    live: 'https://ezar.github.io/ColorGame/',
    repo: 'https://github.com/ezar/ColorGame',
    year: 2024,
    featured: false,
  },
  {
    id: 'patches',
    title: 'Patches',
    glyph: 'Pa',
    cat: 'game',
    desc: 'Shikaku-inspired grid puzzle. Drag rectangles to fill the board, each containing exactly one numbered seed. Undo, hints, confetti on win.',
    tech: ['TypeScript', 'Vite', 'PWA'],
    live: 'https://precious-platypus-837e9b.netlify.app',
    repo: 'https://github.com/ezar/PatchesGame',
    year: 2024,
    featured: false,
  },
  {
    id: 'may4',
    title: 'May The 4th',
    glyph: 'M4',
    cat: 'game',
    desc: 'Star Wars mobile arcade. Tilt your phone to move, tap to deflect blasters, charge the Force bar and unleash a screen-clearing blast across 5 waves.',
    tech: ['React', 'Canvas', 'Zustand', 'Gyroscope API'],
    live: 'https://ezar.github.io/may4-game/',
    repo: 'https://github.com/ezar/may4-game',
    year: 2025,
    featured: false,
  },
];

window.CATEGORIES = {
  game:    { label: 'Game',    plural: 'Games',    legacyEmoji: '🎮' },
  project: { label: 'Project', plural: 'Projects', legacyEmoji: '🏠' },
  mcp:     { label: 'MCP',     plural: 'MCP',      legacyEmoji: '🤖' },
  agent:   { label: 'Agent',   plural: 'Agents',   legacyEmoji: '📈' },
};

window.TECH_HIGHLIGHT = ['React', 'TypeScript', 'Python', 'Claude AI', 'PWA', 'Next.js', 'Vue 3'];
